
name: {{name}}
model: WRF-CMAQ
description: "WRF-CMAQ 2 day forecast using ACCESS-G boundary conditions runs on SDC CAS partition"
code_repository_url: git@bitbucket.org:oehcas/wrf-cmaq.git
code_commit_hash: 4f179e93f9745d89c53e93df31ab198460117323

# Setup options
setup:
    start_datetime: {{today}}T00
    run_length_hours: 48
    forcing_interval_hours: 3
    setup_script: setup.sh

# Build options
build:
    build_name: DPIE-SDC-intel-AVX2
    build_script: build.sh

# Runtime options
run:
    run_script: run.sh
    queue_name: CAS
    wrf:
        met_boundary_conditions: ACCESS-G
        num_cpus: 108
    cmaq:
        d01:
            num_cpus: 108
        d02:
            num_cpus: 72
        d03:
            num_cpus: 108
    mcip:
        static_grid_dir: {{base_dir}}/input/MCIP_static_grids

emissions:
    smoke: 'CSEM'

site:
    machine_name: {{machine_name}}
    mems_output: /mnt/scratch_lustre/nhannah/workflows/emissions/
    bucket_url: file://{{esme_bucket_cache}}/
    base_dir: {{base_dir}}
