
name: {{name}}
model: WRF-CMAQ
description: "WRF-CMAQ 2 day forecast using ACCESS-G boundary conditions"
code_repository_url: git@bitbucket.org:oehcas/wrf-cmaq.git
code_commit_hash: 7bd6f3725dcfb58b0b0d7e2c59f1d8d7af48de87

# Setup options
setup:
    start_datetime: {{yesterday}}T06
    run_length_hours: 48
    forcing_interval_hours: 3
    setup_script: setup.sh

# Build options
build:
    build_script: build.sh

# Runtime options
run:
    run_script: run.sh
    queue_name: CAS
    wrf:
        met_boundary_conditions: ACCESS-G
        num_cpus: 108
    cmaq:
        d01:
            num_cpus: 108
        d02:
            num_cpus: 72
        d03:
            num_cpus: 108

site:
    machine_name: {{machine_name}}
    bucket_url: file://{{esme_bucket_cache}}/
    base_dir: {{base_dir}}
