
name: {{name}}
model: WRF-CMAQ
description: "WRF-CMAQ 2 day forecast using ACCESS-G boundary conditions runs on SDC general partition"
code_repository_url: git@bitbucket.org:oehcas/wrf-cmaq.git
code_commit_hash: 06d89021f32cb214a1fde6c00c095c6fcdf9c074

# Setup options
setup:
    start_datetime: 2021-09-06T06
    run_length_hours: 48
    forcing_interval_hours: 3
    setup_script: setup.sh

# Build options
build:
    build_name: DPIE-SDC-intel-general
    build_script: build.sh

# Runtime options
run:
    run_script: run.sh
    queue_name: general
    wrf:
        met_boundary_conditions: ACCESS-G
        num_cpus: 80
    cmaq:
        d01:
            num_cpus: 80
        d02:
            num_cpus: 80
        d03:
            num_cpus: 80
    mcip:
        static_grid_dir: {{base_dir}}/input/MCIP_static_grids

emissions:
    smoke: 'CSEM'


site:
    machine_name: SDC
    mems_output: /mnt/scratch_lustre/nhannah/workflows/emissions/
    bucket_url: file://{{esme_bucket_cache}}/
    base_dir: {{base_dir}}
