
name: {{name}}
model: WRF-CMAQ
description: "WRF-CMAQ base Policy Mode using ERA5 boundary conditions"
code_repository_url: git@bitbucket.org:oehcas/wrf-cmaq.git
code_commit_hash: adcc78d57d7526135d6b765d6b0786b4e53f3482

# Setup options
setup:
    start_datetime: 2020-01-01T00
    run_length_hours: 744
    forcing_interval_hours: 1
    setup_script: setup.sh

# Build options
build:
    build_script: build.sh

# Runtime options
run:
    run_script: run.sh
    wrf:
        met_boundary_conditions: ERA5

site:
    machine_name: {{machine_name}}
    bucket_url: file://{{esme_bucket_cache}}/
    base_dir: {{base_dir}}
