
name: {{name}}
model: WRF-CMAQ
description: "WRF-CMAQ base Policy Mode using ERA5 boundary conditions"
code_repository_url: git@bitbucket.org:oehcas/wrf-cmaq.git
code_commit_hash: 316072c4b1b7efb8d814e8ffacda9fe7e91a14a2

# Setup options
setup:
    start_datetime: 2020-01-01T00
    run_length_hours: 744
    forcing_interval_hours: 1
    setup_script: setup.sh

# Build options
build:
    build_script: build.sh

# Runtime options
run:
    run_script: run.sh
    queue_name: general
    wrf:
        met_boundary_conditions: ERA5
        num_cpus: 80
    cmaq:
        d01:
            num_cpus: 80
        d02:
            num_cpus: 80
        d03:
            num_cpus: 80

emissions:
    smoke: 'GFAS'

site:
    machine_name: {{machine_name}}
    mems_output: /mnt/scratch_lustre/nhannah/workflows/emissions/
    bucket_url: file://{{esme_bucket_cache}}/
    base_dir: {{base_dir}}
